CREATE TABLE MODE (
    id   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    name VARCHAR(255),
    mode_code VARCHAR(50),
    CONSTRAINT mode_pk PRIMARY KEY (id)
);
