CREATE TABLE WEIGHINGS (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
brutto FLOAT,
netto FLOAT,
tare_id INTEGER,
clogging FLOAT,
trash FLOAT,
metal_id INTEGER,
waybill_id INTEGER,
CONSTRAINT waybill_id_ref FOREIGN KEY (waybill_id) REFERENCES WAYBILLS(id))

