INSERT INTO properties (name, value)
VALUES ('password', '2af9b1ba42dc5eb01743e6b3759b6e4b'),
       ('endpoint.camera1', 'rtsp://login:password@ip:554/RVi/1/1'),
       ('endpoint.camera2', 'rtsp://login:password@ip:554/RVi/1/1'),
       ('endpoint.api', 'https://db.avs.com.ru/'),
       ('endpoint.api.token', 'api/token'),
       ('endpoint.api.metal', 'reference/metal/list'),
       ('endpoint.api.department', 'api/department'),
       ('endpoint.api.export', 'api/export'),
       ('endpoint.api.login', 'login'),
       ('endpoint.api.password', 'password'),
       ('scale1.name', 'Оптовые весы'),
       ('scale1.type', '1'),
       ('scale1.port', 'COM5'),
       ('scale1.speed', '9600'),
       ('scale1.command', '4A'),
       ('scale2.name', 'Розничные весы'),
       ('scale2.type', '2'),
       ('scale2.port', 'COM6'),
       ('scale2.speed', '4800'),
       ('scale2.command', '4A'),
       ('image.path', 'C:/tmp/'),
       ('department.id', '0'),
       ('ignore.prop', 'department.id,password');
