CREATE TABLE SCALES (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    name VARCHAR(255),
    port VARCHAR(255),
    type INTEGER,
    camera VARCHAR(255),
    mode_id INTEGER,
    CONSTRAINT scales_pk PRIMARY KEY (id),
    CONSTRAINT mode_id_ref FOREIGN KEY (mode_id) REFERENCES MODE(id)
);
