CREATE TABLE WAYBILLS (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
waybill INTEGER,
department_id INTEGER,
date_create DATE,
time_create TIME,
comment VARCHAR(255),
upload BOOLEAN,
CONSTRAINT primary_key PRIMARY KEY (id))
